/* eslint-disable @next/next/no-img-element */
'use client';

import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import type { TenantShareAvatarPreset } from '@eggturtle/shared';
import { Home, QrCode, Share2, Sparkles, X } from 'lucide-react';
import QRCode from 'qrcode';

import {
  FloatingActionButton,
  FloatingActionDock,
  floatingActionButtonClass,
  modalCloseButtonClass,
} from '@/components/ui/floating-actions';
import { usePlatformBranding } from '@/lib/branding-client';
import { generateShareComboPoster } from '@/lib/share-combo-poster';
import { dataUrlToBlob, normalizeShareFileName } from '@/lib/share-poster';
import { cn } from '@/lib/utils';

type PublicFloatingActionsProps = {
  permalink?: string;
  useCurrentUrl?: boolean;
  homeHref?: string;
  showHomeButton?: boolean;
  className?: string;
  /** 与默认按钮同一容器内上下排列的额外按钮（如筛选），统一在右侧 */
  children?: ReactNode;
  /** 用户在分享配置里上传的联系二维码 */
  tenantQrImageUrl?: string | null;
  tenantWechatId?: string | null;
  shareCardTitle?: string;
  shareCardSubtitle?: string;
  shareCardPrimaryColor?: string;
  shareCardSecondaryColor?: string;
  shareCardHeroImageUrl?: string | null;
  shareCardAvatarUrl?: string | null;
  shareCardAvatarPreset?: TenantShareAvatarPreset | null;
  shareCardDisplayName?: string | null;
  shareCardAccountLabel?: string | null;
  shareCardStats?: {
    breederCount?: number;
    maleCount?: number;
    femaleCount?: number;
    seriesCount?: number;
    needMatingCount?: number;
    eggsThisYear?: number;
  } | null;
};

const DEFAULT_SHARE_TITLE = '选育溯源档案 · 公开图鉴';
const DEFAULT_SHARE_SUBTITLE = '扫码查看完整公开图鉴与更新动态';

export default function PublicFloatingActions({
  permalink: permalinkProp,
  useCurrentUrl = false,
  homeHref = '/app',
  showHomeButton = true,
  className,
  children,
  tenantQrImageUrl,
  tenantWechatId,
  shareCardTitle,
  shareCardSubtitle,
  shareCardPrimaryColor,
  shareCardSecondaryColor,
  shareCardHeroImageUrl,
  shareCardAvatarUrl,
  shareCardAvatarPreset,
  shareCardDisplayName,
  shareCardAccountLabel,
  shareCardStats,
}: PublicFloatingActionsProps) {
  const branding = usePlatformBranding();
  const [tenantQrOpen, setTenantQrOpen] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [linkQrDataUrl, setLinkQrDataUrl] = useState<string | null>(null);
  const [shareCardDataUrl, setShareCardDataUrl] = useState<string | null>(null);
  const [shareCardLoading, setShareCardLoading] = useState(false);
  const [shareCardError, setShareCardError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [currentUrl, setCurrentUrl] = useState('');

  useEffect(() => {
    if (!useCurrentUrl) return;
    setCurrentUrl(typeof window !== 'undefined' ? window.location.href : '');
  }, [useCurrentUrl]);

  useEffect(() => {
    if (!notice) return;
    const timer = window.setTimeout(() => setNotice(null), 2600);
    return () => window.clearTimeout(timer);
  }, [notice]);

  const permalink = useCurrentUrl ? currentUrl : (permalinkProp ?? '');
  const defaultShareTitle = `${branding.appName.zh} · ${branding.publicCatalogTitleSuffix.zh}`;
  const cardTitle = shareCardTitle?.trim() || defaultShareTitle || DEFAULT_SHARE_TITLE;
  const cardSubtitle = shareCardSubtitle?.trim() || DEFAULT_SHARE_SUBTITLE;

  // 本地生成链接二维码，避免把公开链接发给第三方二维码服务。
  useEffect(() => {
    if (!permalink) {
      setLinkQrDataUrl(null);
      return;
    }

    let cancelled = false;

    void (async () => {
      try {
        const dataUrl = await QRCode.toDataURL(permalink, {
          width: 360,
          margin: 1,
          errorCorrectionLevel: 'H',
        });
        if (!cancelled) {
          setLinkQrDataUrl(dataUrl);
        }
      } catch {
        if (!cancelled) {
          setLinkQrDataUrl(null);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [permalink]);

  useEffect(() => {
    if (!shareOpen || !permalink || !linkQrDataUrl) {
      return;
    }

    let cancelled = false;
    setShareCardLoading(true);
    setShareCardError(null);

    void (async () => {
      try {
        const dataUrl = await generateSharePoster({
          qrDataUrl: linkQrDataUrl,
          title: cardTitle,
          subtitle: cardSubtitle,
          footerLabel: `Generated by ${branding.appName.en}`,
          primaryColor: shareCardPrimaryColor,
          secondaryColor: shareCardSecondaryColor,
          heroImageUrl: shareCardHeroImageUrl,
          avatarUrl: shareCardAvatarUrl,
          avatarPreset: shareCardAvatarPreset,
          displayName: shareCardDisplayName,
          accountLabel: shareCardAccountLabel,
          wechatId: tenantWechatId,
          stats: shareCardStats,
        });

        if (!cancelled) {
          setShareCardDataUrl(dataUrl);
          setShareCardError(null);
        }
      } catch {
        if (!cancelled) {
          setShareCardDataUrl(null);
          setShareCardError('卡片生成失败，请稍后重试。');
        }
      } finally {
        if (!cancelled) {
          setShareCardLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [
    shareOpen,
    permalink,
    linkQrDataUrl,
    branding.appName.en,
    cardTitle,
    cardSubtitle,
    shareCardPrimaryColor,
    shareCardSecondaryColor,
    shareCardHeroImageUrl,
    shareCardAvatarUrl,
    shareCardAvatarPreset,
    shareCardDisplayName,
    shareCardAccountLabel,
    tenantWechatId,
  ]);

  async function handleShareAction() {
    if (!permalink) {
      setError('分享链接尚未就绪，请稍后再试。');
      return;
    }

    const shareText = `${cardTitle}\n${cardSubtitle}`;

    try {
      if (typeof navigator !== 'undefined' && typeof navigator.share === 'function') {
        const blob = shareCardDataUrl ? dataUrlToBlob(shareCardDataUrl) : null;

        if (blob) {
          const file = new File([blob], `${normalizeShareFileName(cardTitle)}.png`, {
            type: 'image/png',
          });
          if (typeof navigator.canShare === 'function' && navigator.canShare({ files: [file] })) {
            await navigator.share({
              title: cardTitle,
              text: shareText,
              url: permalink,
              files: [file],
            });
            return;
          }
        }

        await navigator.share({
          title: cardTitle,
          text: shareText,
          url: permalink,
        });
        return;
      }
    } catch (err) {
      if (err instanceof Error && err.name === 'AbortError') {
        return;
      }
    }

    try {
      await navigator.clipboard.writeText(permalink);
      setNotice('已复制分享链接，可直接粘贴发送。');
    } catch {
      setError('无法调用系统分享，请手动复制链接。');
    }
  }

  function handleDownloadShareCard() {
    if (!shareCardDataUrl) {
      setError('分享卡片仍在生成中，请稍后再试。');
      return;
    }

    const link = document.createElement('a');
    link.download = `${normalizeShareFileName(cardTitle)}-share-card.png`;
    link.href = shareCardDataUrl;
    link.click();
    setNotice('高清分享卡片已开始下载。');
  }

  return (
    <>
      <FloatingActionDock
        className={cn(
          '!z-[55] !bottom-[calc(56px+max(24px,env(safe-area-inset-bottom))+12px)] lg:!bottom-[calc(56px+max(24px,env(safe-area-inset-bottom))+12px)]',
          className,
        )}
      >
        {children}

        <FloatingActionButton
          aria-label="生成分享卡片"
          title="生成分享卡片"
          onClick={() => {
            setShareOpen(true);
            setError(null);
          }}
        >
          <Share2 size={20} />
        </FloatingActionButton>

        <FloatingActionButton
          aria-label="用户联系二维码"
          title="用户联系二维码"
          onClick={() => setTenantQrOpen(true)}
        >
          <QrCode size={20} />
        </FloatingActionButton>

        {showHomeButton ? (
          <a
            href={homeHref}
            aria-label="进入后台"
            title="进入后台"
            className={floatingActionButtonClass}
          >
            <Home size={18} />
          </a>
        ) : null}
      </FloatingActionDock>

      {tenantQrOpen ? (
        <div
          className="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 p-4"
          role="dialog"
          aria-modal="true"
          aria-label="用户联系二维码"
          onClick={() => setTenantQrOpen(false)}
        >
          <div
            className="w-full max-w-sm rounded-3xl border border-black/10 bg-white p-4 shadow-2xl dark:border-white/10 dark:bg-neutral-900"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="mb-3 flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">
                  用户联系二维码
                </p>
                <p className="text-xs text-neutral-500 dark:text-neutral-400">
                  扫码可直接联系当前用户
                </p>
              </div>
              <button
                type="button"
                aria-label="关闭二维码"
                className={modalCloseButtonClass}
                onClick={() => setTenantQrOpen(false)}
              >
                <X size={17} strokeWidth={2.6} />
              </button>
            </div>

            {tenantQrImageUrl ? (
              <img
                src={tenantQrImageUrl}
                alt="用户联系二维码"
                className="mx-auto h-64 w-64 rounded-2xl border border-black/5 bg-white object-cover p-1"
              />
            ) : (
              <div className="mx-auto flex h-64 w-64 flex-col items-center justify-center gap-2 rounded-2xl border border-dashed border-neutral-300 bg-neutral-50 text-center text-xs text-neutral-500 dark:border-white/20 dark:bg-neutral-950/50 dark:text-neutral-400">
                <QrCode size={20} />
                当前用户暂未上传联系二维码
              </div>
            )}

            {tenantWechatId ? (
              <p className="mt-3 text-center text-sm text-neutral-700 dark:text-neutral-300">
                微信号：<span className="font-mono font-semibold">{tenantWechatId}</span>
              </p>
            ) : null}
          </div>
        </div>
      ) : null}

      {shareOpen ? (
        <div
          className="fixed inset-0 z-[60] flex items-center justify-center bg-black/55 p-3"
          role="dialog"
          aria-modal="true"
          aria-label="分享卡片"
          onClick={() => setShareOpen(false)}
        >
          <div
            className="w-full max-w-md rounded-3xl border border-black/10 bg-white p-4 shadow-2xl dark:border-white/10 dark:bg-neutral-900"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="mb-3 flex items-start justify-between gap-3">
              <div>
                <p className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-[0.18em] text-amber-700 dark:bg-amber-400/15 dark:text-amber-300">
                  <Sparkles size={12} />
                  Share Card
                </p>
                <p className="mt-2 text-base font-semibold text-neutral-900 dark:text-neutral-100">
                  高质量二维码分享卡片
                </p>
                <p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">
                  可下载 PNG，或直接调用系统分享。
                </p>
              </div>
              <button
                type="button"
                aria-label="关闭分享卡片"
                className={modalCloseButtonClass}
                onClick={() => setShareOpen(false)}
              >
                <X size={17} strokeWidth={2.6} />
              </button>
            </div>

            <div className="overflow-hidden rounded-2xl border border-black/10 bg-neutral-100 p-2 dark:border-white/10 dark:bg-neutral-950/60">
              {shareCardLoading ? (
                <div className="flex h-[420px] items-center justify-center rounded-xl bg-white text-sm text-neutral-500 dark:bg-neutral-900 dark:text-neutral-400">
                  正在生成高清卡片...
                </div>
              ) : shareCardDataUrl ? (
                <img
                  src={shareCardDataUrl}
                  alt="分享卡片预览"
                  className="h-auto w-full rounded-xl bg-white shadow-[0_10px_24px_rgba(0,0,0,0.16)]"
                />
              ) : (
                <div className="flex h-[420px] items-center justify-center rounded-xl bg-white px-6 text-center text-sm text-neutral-500 dark:bg-neutral-900 dark:text-neutral-400">
                  {shareCardError || '分享卡片暂不可用'}
                </div>
              )}
            </div>

            <p className="mt-3 line-clamp-2 rounded-xl border border-black/5 bg-neutral-50 px-3 py-2 text-xs text-neutral-600 dark:border-white/10 dark:bg-neutral-950/50 dark:text-neutral-300">
              {permalink || '链接生成中...'}
            </p>

            <div className="mt-3 grid grid-cols-2 gap-2">
              <button
                type="button"
                onClick={handleDownloadShareCard}
                className="inline-flex min-h-10 items-center justify-center rounded-full border border-black/10 bg-white px-3 text-sm font-semibold text-neutral-800 transition hover:bg-neutral-50 dark:border-white/15 dark:bg-neutral-900 dark:text-neutral-100"
              >
                下载 PNG
              </button>
              <button
                type="button"
                onClick={() => void handleShareAction()}
                className="inline-flex min-h-10 items-center justify-center rounded-full bg-neutral-900 px-3 text-sm font-semibold text-white transition hover:bg-neutral-800 dark:bg-[#FFD400] dark:text-neutral-900 dark:hover:bg-[#f1ca00]"
              >
                立即分享
              </button>
            </div>
          </div>
        </div>
      ) : null}

      {error ? (
        <div
          className="fixed left-4 right-4 z-[70] rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-800 dark:bg-red-950/90 dark:text-red-200 sm:left-auto sm:right-6 sm:max-w-xs"
          role="alert"
        >
          {error}
          <button
            type="button"
            onClick={() => setError(null)}
            className="ml-2 font-semibold underline"
          >
            关闭
          </button>
        </div>
      ) : null}

      {notice ? (
        <div
          className="fixed left-4 right-4 z-[70] rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950/90 dark:text-emerald-200 sm:left-auto sm:right-6 sm:max-w-xs"
          role="status"
        >
          {notice}
        </div>
      ) : null}
    </>
  );
}

type SharePosterPayload = {
  qrDataUrl: string;
  title: string;
  subtitle: string;
  footerLabel?: string;
  primaryColor?: string;
  secondaryColor?: string;
  heroImageUrl?: string | null;
  avatarUrl?: string | null;
  avatarPreset?: TenantShareAvatarPreset | null;
  displayName?: string | null;
  accountLabel?: string | null;
  wechatId?: string | null;
  stats?: {
    breederCount?: number;
    maleCount?: number;
    femaleCount?: number;
    seriesCount?: number;
    needMatingCount?: number;
    eggsThisYear?: number;
  } | null;
};

async function generateSharePoster(payload: SharePosterPayload): Promise<string> {
  return generateShareComboPoster({
    title: payload.title,
    subtitle: payload.subtitle,
    qrDataUrl: payload.qrDataUrl,
    primaryColor: payload.primaryColor,
    secondaryColor: payload.secondaryColor,
    heroImageUrl: payload.heroImageUrl,
    avatarUrl: payload.avatarUrl ?? null,
    footerLabel: payload.footerLabel ?? null,
    displayName: payload.displayName ?? null,
    accountLabel: payload.accountLabel ?? null,
    avatarPreset: payload.avatarPreset ?? null,
    contactLabel: payload.wechatId?.trim() ? `微信号 ${payload.wechatId.trim()}` : null,
    stats: payload.stats,
  });
}
