export const ErrorCode = {
  None: 'NONE',
  ApiUnavailable: 'API_UNAVAILABLE',
  InvalidRequestPayload: 'INVALID_REQUEST_PAYLOAD',
  InvalidCode: 'INVALID_CODE',
  ExpiredCode: 'EXPIRED_CODE',
  Unauthorized: 'UNAUTHORIZED',
  Forbidden: 'FORBIDDEN',
  TenantNotFound: 'TENANT_NOT_FOUND',
  TenantMemberNotFound: 'TENANT_MEMBER_NOT_FOUND',
  NotTenantMember: 'NOT_TENANT_MEMBER',
  TenantSlugConflict: 'TENANT_SLUG_CONFLICT',
  TenantNotSelected: 'TENANT_NOT_SELECTED',
  ProductNotFound: 'PRODUCT_NOT_FOUND',
  ProductEventNotFound: 'PRODUCT_EVENT_NOT_FOUND',
  ProductImageNotFound: 'PRODUCT_IMAGE_NOT_FOUND',
  ProductCertificateNotFound: 'PRODUCT_CERTIFICATE_NOT_FOUND',
  ProductCertificateEligibilityFailed: 'PRODUCT_CERTIFICATE_ELIGIBILITY_FAILED',
  ProductCertificateQuotaExceeded: 'PRODUCT_CERTIFICATE_QUOTA_EXCEEDED',
  ProductCertificateAlreadyVoid: 'PRODUCT_CERTIFICATE_ALREADY_VOID',
  ProductCouplePhotoNotFound: 'PRODUCT_COUPLE_PHOTO_NOT_FOUND',
  SaleBatchNotFound: 'SALE_BATCH_NOT_FOUND',
  SaleBatchEventMismatch: 'SALE_BATCH_EVENT_MISMATCH',
  SaleBatchQuantityExceeded: 'SALE_BATCH_QUANTITY_EXCEEDED',
  SaleAllocationNotFound: 'SALE_ALLOCATION_NOT_FOUND',
  SaleSubjectMediaNotFound: 'SALE_SUBJECT_MEDIA_NOT_FOUND',
  SeriesNotFound: 'SERIES_NOT_FOUND',
  BreederNotFound: 'BREEDER_NOT_FOUND',
  FeaturedProductNotFound: 'FEATURED_PRODUCT_NOT_FOUND',
  FeaturedProductConflict: 'FEATURED_PRODUCT_CONFLICT',
  ShareNotFound: 'SHARE_NOT_FOUND',
  ShareSignatureInvalid: 'SHARE_SIGNATURE_INVALID',
  ShareSignatureExpired: 'SHARE_SIGNATURE_EXPIRED',
  TenantSubscriptionInactive: 'TENANT_SUBSCRIPTION_INACTIVE',
  TenantSubscriptionPlanInsufficient: 'TENANT_SUBSCRIPTION_PLAN_INSUFFICIENT',
  TenantSubscriptionQuotaExceeded: 'TENANT_SUBSCRIPTION_QUOTA_EXCEEDED',
  SubscriptionActivationCodeInvalid: 'SUBSCRIPTION_ACTIVATION_CODE_INVALID',
  SubscriptionActivationCodeExpired: 'SUBSCRIPTION_ACTIVATION_CODE_EXPIRED',
  SubscriptionActivationCodeDisabled: 'SUBSCRIPTION_ACTIVATION_CODE_DISABLED',
  SubscriptionActivationCodeRedeemLimitReached: 'SUBSCRIPTION_ACTIVATION_CODE_REDEEM_LIMIT_REACHED',
  AiFeatureDisabled: 'AI_FEATURE_DISABLED',
  AiModelNotConfigured: 'AI_MODEL_NOT_CONFIGURED',
  AiRateLimited: 'AI_RATE_LIMITED',
  QuotaExceeded: 'QUOTA_EXCEEDED',
  AiProviderError: 'AI_PROVIDER_ERROR'
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
